### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by spencerlepine** [spencerlepine/portfolio-site#5]
# REDESIGN Steps
- [x] Stripped away all existing Tailwind CSS
- [x] Created [Figma Designs](https://www.figma.com/file/nlQpEhXufCtXz4iSYbQDny/Portfolio-Site?node-id=9%3A209) for landing page
- [x] Implement Tailwind CSS theme context and color configuration
- [x] Add desktop styles for landing page
- [x] Make SVG files for each of the tech icons from [this site](https://svgporn.com/#search=html)
- [x] Added dark mode colors to configuration
- [x] Editing bare bones styles for blog and portfolio page
- [x] run lighthouse tests
~~- [ ] Make landing page responsive~~
~~- [ ] work on blog page styles~~
~~- [ ] work on projects page styles~~
~~- [ ] make blog page responsive~~
~~- [ ] make project page responsive~~
~~- [ ] finish rediesigning article~~
~~- [ ] add animations~~
~~- [ ] make linkedin post?~~

## My best projects:
Woofer MERN App - https://github.com/spencerlepine/woofer
Atelier Ecommerce API - https://github.com/sdc-bareminimum/project-catwalk-related-service
SquidShop Ecommerce Web App - https://github.com/spencerlepine/squidshop-ecommerce
HelloHealth Web App - https://github.com/Blue-Ocean-Team-1/HelloHealth
QuickCart Web App - https://github.com/spencerlepine/quickcart

## Best ReadMe: https://github.com/spencerlepine/woofer
 
--- 
## Make sure every project has this:
[https://github.com/spencerlepine](https://github.com/spencerlepine/woofer)
- [x] Make sure GitHub pins are updated
- [ ] Clean README describing:
- Title and Link to demo	
- Main idea /Goal/Theme of the app
- Context, time frame, team/solo, to learn a technology
- Technologies the app was built with
- Features of the app (like resume bullet points)
- Screenshot (GIF preferably)
- Extra at bottom:
Setup Instructions
Technologies Used Links
My links

- [ ] Readable page on portfolio site
